### ISSUE TITLE
printing error "Error: you must have available printer, to use printed"

### ISSUE THREAD

**Issue by spchamath** [mrf345/FQM#100]
"Error: you must have available printer, to use printed" 

FQM give this error when trying to print the ticket. tried different Epson and Posiflex printers but nothing worked. can anyone help me? test print comes without any issues and the printer is shared with the same name.

**Comment by mrf345** [comment]
Hi @spchamath , are you running FQM from the source-code or a binary ?

There was an issue with printing that got resolved in https://github.com/mrf345/FQM/issues/93 ,
However i'm yet to generate to binaries for a new release.

**Comment by mrf345** [comment]
Seems to be resolved with https://github.com/mrf345/FQM/issues/93 ,I'm closing this one for now.
