### ISSUE TITLE
Issue in deploy the FQM in Cloud

### ISSUE THREAD

**Issue by Anuradha677** [mrf345/FQM#102]
I am getting the below error while running command "python3 run.py"

qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.
Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, webgl, xcb.

Aborted (core dumped)

Please help me to fix this.

**Comment by mrf345** [comment]
First time seeing this one 🤔 what Linux distribution are you deploying to ?
Probably it's time to separate CLI from GUI completely and create `requirements/deploy.txt`

**Comment by mrf345** [comment]
I'm about to merge a PR that hopefully helps you  to avoid the issue altogether. Just use `requirements/deploy.txt` instead of `requirements/main.txt` and run it with `python run.py --cli`
