### ISSUE TITLE
Add German language support

### ISSUE THREAD

**Issue by QueueManager1** [mrf345/FQM#104]
Hey.
Your Project ist quite great!
Is there any possibility to get a german language inclueded?
Or is there the possibility to only play the notification sound without the text-to-speech?

When i disable the text-to-speech there is also nno notification sound. 

Is there any help for me?

**Comment by mrf345** [comment]
Hi, glad you've liked it!

Surely, I was able to reproduce the audio notification issue being automatically disabled when the TTS is disabled. I'm pulling it into a separate issue, that i'll be resolving today. And leave this as an enhancement for adding German language support.

**Comment by mrf345** [comment]
I've added a quick guide on how to add a new announcement language support [here](https://github.com/mrf345/FQM/blob/master/docs/localization.md#text-to-speech-localization)
It's fairly easy, just two lines of code change.

@QueueManager1 feel free to add it. Or if someone else wants to take it.
