### ISSUE TITLE
Os requirements

### ISSUE THREAD

**Issue by pepsy80** [mrf345/FQM#11]
Hi , I try to setup on Mint 19 xfce 32 Bit unsuccessfull .

Wich are the OS requirements ?

**Comment by mrf345** [comment]
Hi, sorry for the late replay. I don't think the issue's with your OS not meeting the project requirements. But the build requirements were outdated and some of them got deprecated. I've merged a PR that addresses the issue https://github.com/mrf345/FQM/pull/18
