### ISSUE TITLE
The Log give me this every second

### ISSUE THREAD

**Issue by ernestoluciano** [mrf345/FQM#116]
[2020-06-04 11:58:12] "GET /repeat_announcement/True HTTP/1.1" 302 691 0.121707

**Comment by ernestoluciano** [comment]
The announcement is looping, it only happens in Debian, i tested in mac with no problem, only debian have a problem

**Comment by mrf345** [comment]
Mind sharing the browser you're using and its version ?

**Comment by ernestoluciano** [comment]
Chrome Newest Version

ATT.:

Lic. Ernesto Luciano
CEO & Founder CORPORACIÓN LUCIANO BATISTA
Puerto Plata · República Dominicana
Tel.: (809) 571-3010
Móvil: (829) 760-1571

No me imprimas si no es necesario. Protejamos el medio ambiente.

POLÍTICA DE PRIVACIDAD: Este mensaje y sus datos adjuntos pueden contener información confidencial o legalmente protegida y no puede ser utilizada ni divulgada por personas diferentes a su destinatario. Si por error, recibe este mensaje, por favor avise inmediatamente a su remitente y destruya toda copia que tenga del mismo. Cualquier uso, divulgación, copia, distribución, impresión o acto derivado del conocimiento total o parcial de este mensaje sin autorización de CORPORACION LUCIANO BATISTA y/o sus dependientes, será sancionado de acuerdo con las normas legales vigentes. De otra parte, al destinatario se le considera custodio de la información contenida y debe velar por su confidencialidad, integridad y privacidad.

Este correo puede contener datos en formatos PDF: Puede descargar un lector desde el siguiente enlace: LECTOR ADOBE PDF (GRATIS)

**Comment by mrf345** [comment]
Thanks! will give reproducing it a shot.

**Comment by mrf345** [comment]
*For future reference*: the probable core cause is https://github.com/mrf345/FQM/issues/105
