### ISSUE TITLE
Printer Log

### ISSUE THREAD

**Issue by ernestoluciano** [mrf345/FQM#122]
Traceback (most recent call last):
  File "/root/FQM/app/views/core.py", line 132, in serial
    printer = assign(int(ticket_settings.vendor), int(ticket_settings.product),
ValueError: invalid literal for int() with base 10: ' '

**Comment by mrf345** [comment]
Hi again @ernestoluciano , i'm about to merge a PR https://github.com/mrf345/FQM/pull/123 that resolves the issue.
Please let me know if the issue still persists.
