### ISSUE TITLE
Multimedia page doesn't work

### ISSUE THREAD

**Issue by chicastaxadmin** [mrf345/FQM#14]
When you click on Multimedia page to upload content like logo and videos, as soon as you click the link it sign you out and says "[Error: something wrong, or the page is non-existing.]"

**Comment by mrf345** [comment]
The referenced merged PR resolves the issue:

- Before:
![multimedia_before](https://user-images.githubusercontent.com/26286907/69904078-189f1380-13dd-11ea-9dbe-19c3ab560d7a.png)

- After:
![multimedia_after](https://user-images.githubusercontent.com/26286907/69904081-1e94f480-13dd-11ea-8f9e-14f181834f32.png)
