### ISSUE TITLE
The ability for each office/user to assign tickets to different users

### ISSUE THREAD

**Issue by nukebrainia9** [mrf345/FQM#158]
could be cool. Say I am in a hospital. I just saw a patient and want to refer them to place them on a different queue.

**Comment by mrf345** [comment]
Nice idea. Currently a ticket has to be assigned to any given task whenever it's created. And tasks can belong to many offices if they're common tasks `many to many`.

So the feature will allow any authorized user to change to which task a given ticket's belong to ?
