### ISSUE TITLE
Supplement for FQM: push-button

### ISSUE THREAD

**Issue by picsldev** [mrf345/FQM#160]
_Greetings to all_

With the idea of helping in this project, I have made an outline of what could be a simplified push button that allows the basic management of a work queue assigned to a certain computer.

As long as the program does not have a stable API, I think that the simplest, to be able to manage the basic operations, from an external button, is to use the `curl` command.

The button would be individually configurable, on each computer.

As fixed parameters, you should know the IP address and port where the server is running.

Once a connection test is performed, the push button configuration program should be populated with the options available from the server, so that you can choose which queue you want to work on or any other parameter that is defined on the server (¿json?).

Correctly configuring the button, using the data coming from the server, is a relatively simple task, although it is necessary to plan the specific way in which it should be done.

(Note: take security into account when allowing the necessary accesses)

In order to allow the work from an external application, it is necessary to establish a simple form that allows the exchange of information in a simple way.

To be able to work from the button, it would be necessary to enable at least the following calls:

_Status_: View the current number, in the active queue.
_Forward_: Advance the active queue counter.
_Backward_: Reverse the counter of the active queue.

Sure, it will take more calls, but in this case, let's say that these are the most basic.

In order to keep moving forward, I wanted to ask if there is an example of how I should currently make these 3 calls.

Is there an example?

Next I leave a gif with a mockup made using `PySimpleGui`.

![Mockup-Push-Boutton-FQM](https://user-images.githubusercontent.com/19928827/85753767-717d2300-b704-11ea-84ef-e5723b18cfe3.gif)

**Comment by mrf345** [comment]
Hello @picsldev 

Thanks again for the well detailed issue.

As you've mentioned the project lacks an API at the moment. And I think the next logical step is to create one.
Probably we should start by exposing the basic `app/view/core.py` endpoints, as an API with its own authentication protocol.
Most likely it will be a REST API with a token based authentication.

To achieve that milestone we'll have to split it into smaller tasks:
- Create an API module with `Flask-Restx` or an equivalent
- Add token authentication handlers with `Flask-HTTPAuth` which we are already using
- Add front-end interface to handle adding, updating and deleting tokens

One currently missing requirement is "moving backward" that will need to be implemented in both the `views` and `API`.

For the GUI client application. I think the best approach is to keep the client decoupled from the server. So in production will end up with two different executables `FQM.exe` the server and  `FQM-client.exe`. The server is already using `PyQT5` as an optional GUI, so most probably we'll be using it for the client too. i imagine the requirements for it to be:

- Create base client GUI window
- Add window to handle connecting and authenticating with server
- Add tray column to show current ticket
- Add tray actions  to `forward ticket`, `backward ticket`
- Add core functionalities like exit and click handlers

That's all i can think of at this point 🤔 but certainly the requirements will change as we start the actual implementation.
I will have the capacity to help with most of the REST API back-end tasks, to ship it in the upcoming release `0.9` but certainly not enough free time to implement the client application.

happy to hear your thoughts and suggestions on how to move forward.

**Comment by picsldev** [comment]
Hi, sorry for replying so late ...

I am working on creating a good structure for FQM-Client.

The premises that I use for the client are:
- Multiplatform (linux, windows, mac ..., but with the possibility of being used / ported to IOS, Android)
- It can be used with or without a gui
- The graphical interface, for consistency, develop it using PyQt5

At the moment, those are the requirements that I have set for myself. If you want to add any more, for the initial version, you are on time :-)

On the other hand, it would be nice to have a place to upload some code while I am working, although I can continue working locally and let you know when there is something useful to upload. I don't know if it should be a separate project or not ... you decide :-)

**Comment by mrf345** [comment]
Hello, no worries!

Awesome happy to hear you're making progress ☺️
The requirements sound perfectly on point to me. I think it will be a good idea to start a new project for it, since they will be completely decoupled from each other. But either way works for me, so it's up to you. I'll be happy to help out with code-reviews and small contributions whenever a prototype is ready. And as mentioned earlier i will hopefully be adding the REST API, in the upcoming major release `0.9`.

**Comment by mrf345** [comment]
Hello @picsldev , I've recently added the API backend endpoints that will make this implementation possible.
Make sure to:

1. Generate an authentication token, follow [this demo](https://github.com/mrf345/FQM/pull/224#issue-485402326).
2. From within your python code, you can run the following to list all tickets, for example:

```python
import requests
from http import HTTPStatus


TOKEN = 'b77233f2ae9248d39dc928cea934424e'
BASE = 'http://127.0.0.1:8080/api/v1'

headers = {'Authorization': TOKEN}
response = requests.get(f'{BASE}/tickets', headers=headers)


if response.status_code == HTTPStatus.OK:
    for ticket in response.json():
       # Do stuff with tickets, just printing
       print(f'{ticket["id"]}. {ticket["number"]} [Waiting: {not ticket["p"]}]')
else:
    print(response.json().get('message', 'Error: something went wrong'))
``` 

3. Check out the full API documentation from `Administration > API > API documentation`


I'm closing this issue, for now. Please do let me know if you face any issues using it.
