### ISSUE TITLE
automatically lower down video volume when ticket is pulled and return to normal when announcement end

### ISSUE THREAD

**Issue by xinesooi84** [mrf345/FQM#171]
as per title, would love to have these enhancement as sometimes when ticket is pulled, video sound is louder than the announcement... would like it to automatically lower down it and return to normal once announcement end...

really appreciate your works and time for developing these...

**Comment by mrf345** [comment]
Nice suggestion, I'm about to merge a PR https://github.com/mrf345/FQM/pull/177 that adds it.
 
My pleasure!

**Comment by xinesooi84** [comment]
hi mohamed,

i had updated the file, but the number does not refresh when i pulled a ticket. i do look on the changes at the source code and when i comment out the **Player.doAfter(function() { $('video').prop('muted', false) })** the number do refresh and the volume is muted but do not unmute after the accouncement end...

not sure if these is a bug, but do advice if i am wrong somewhere...

**Comment by mrf345** [comment]
Hello! It sounds like a browser's cache issue. Clear out your browser's cache and give it another try.

**Comment by xinesooi84** [comment]
hi, i had tried to clear the browser cache and its working... thanks for the advice...

i might have another issue on these...

i had set the **Type of announcement and notification repeating** to **Each** and **Number of announcement repeating** to **Two Times** in order to set the announcement  to repeat twice... during the first announcement, the audio indeed had been muted, but when the announcement repeated for the second time, the audio automatically unmuted and played together with the announcement...

if i changed the **Type of announcement and notification repeating** to **whole**, the announcement will speak out as **undefined please proceed to the office number** indefinitely...

**Comment by mrf345** [comment]
Glad it worked! I missed testing the new changes with the different types of repeats that's what has caused the bug you've recently encountered. i'm about to merge PR https://github.com/mrf345/FQM/pull/185 that fixes it. Please let me know if the issue still persists.

**Comment by xinesooi84** [comment]
i had tested and its working perfectly fine now... thanks a lot...
