### ISSUE TITLE
TTS of registered tickets starting with 0 pronounced incorrectly

### ISSUE THREAD

**Issue by Ruuji187** [mrf345/FQM#174]
It reads "001" as "O-O-One". Could be better if it reads it as "One".
Example: "040" is announced as "O-Four-O". It should be announced as "Forty".

**Comment by mrf345** [comment]
I'm not able to reproduce the issue. I tested it in English and Arabic seems to work as expected.  Also the system should start incrementing tickets from `100` so you should never face a scenario where a ticket is `001` or `010`, same with the offices numbers if you enter `030` it will automatically change it to `30` and it's pronounced correctly. 

- What version of FQM you're running ?
- What languages are you using ?
- Can you include a screenshots or steps on how to reproduce the issue ?

**Comment by mrf345** [comment]
@Ruuji187 i'm about to merge a PR https://github.com/mrf345/FQM/pull/178 that resolves it. Please let me know if the issue still persists.

**Comment by Ruuji187** [comment]
I'm using FQM v0.8 beta. I only use en-us. I somehow found a solution to this. I tried putting "<double space> + 1" instead of "001".
I also want to request that the announcement could say a phrase before the number (ticket) e.g.: "Client number 1, please proceed to table number 5."
Thank you!

Sent from Yahoo Mail on Android 
 
  On Thu, Jul 9, 2020 at 3:27 AM, Mohamed Feddad<notifications@github.com> wrote:   


I'm not able to reproduce the issue. I tested it in English and Arabic seems to work as expected. Also the system should start incrementing tickets from 100 so you should never face a scenario where a ticket is 001 or 010, same with the offices numbers if you enter 030 it will automatically change it to 30 and it's pronounced correctly.
   
   - What version of FQM you're running ?
   - What languages are you using ?
   - Can you include a screenshots or steps on how to reproduce the issue ?

**Comment by mrf345** [comment]
Supporting custom TTS announcements is not implemented yet , probably won't be anytime soon. You can us `Customization > Aliases` instead, but it doesn't support any language other than English currently, feel free to open another issue if you wan to add support for another language.

Most welcome!
