### ISSUE TITLE
Request to input alphanumeric value in 'office'

### ISSUE THREAD

**Issue by jorgeb24** [mrf345/FQM#179]
Requesting to input alphanumeric value in 'office' .
Thank you.

**Comment by mrf345** [comment]
Hi @jorgeb24 , i'm about to merge a PR https://github.com/mrf345/FQM/pull/180 that resolves it. Please let me know if any new issues occur as a result.
Most welcome!

**Comment by jorgeb24** [comment]
Thank you very much.
