### ISSUE TITLE
Waiting Tickets Number

### ISSUE THREAD

**Issue by Ruuji187** [mrf345/FQM#188]
Should let the admin to opt out to whether or not to display the 'number' before the waiting tickets.
![Screenshot_2020-07-10 CISQM - Display Screen](https://user-images.githubusercontent.com/67957694/87110631-161d6a00-c29a-11ea-9ca7-ee8b9771582d.png)

**Comment by abdou0202** [comment]
how can you change the tickets number? like 01.02.03....etc
its always 101.102.....
