### ISSUE TITLE
Print Company name in the tickets

### ISSUE THREAD

**Issue by stelmobarbosa** [mrf345/FQM#193]
Is it possible to costumize the text in the header of the printed ticket?

**Comment by mrf345** [comment]
No, it's not possible. Nonetheless, it is an important feature to add prior to `1.0`  release.

**Comment by Nerdtality** [comment]
You can download the project and compile it yourself. You can edit the app/printer.py and customize it.

I used this method to fix this issue, #229

**Comment by Nerdtality** [comment]
Look at line # 160

Hyperlink:
https://github.com/mrf345/FQM/blob/master/app/printer.py#L160
