### ISSUE TITLE
Tokens Number squence is not reseting

### ISSUE THREAD

**Issue by KsAmJ** [mrf345/FQM#199]
the tokens numbers keep incrementing is this the default behavior as our business depends on resetting the visits numbers each day from zero

**Comment by mrf345** [comment]
There's a rest button that can be found in `Office`  or `All offices` views:

![image](https://user-images.githubusercontent.com/26286907/88682622-8aaa3280-d0fb-11ea-8047-c7d40ef16403.png)

**However** the default behavior of resetting offices includes deleting all the office's existing tickets. So i guess this is a feature request `enhancement` to reset tickets increment without deleting them ?

**technical notes**:
currently we're getting the latest processed ticket "specific to office if `Global pulling` flag setting is disabled" from tickets ordered by `number` and  then  increment that number and generate a new ticket with it. Probably we should use a descending `id` order instead.

**Comment by KsAmJ** [comment]
So should I request it as a feature? And what the propabilty and how long
would it take to make such thing?

**Comment by mrf345** [comment]
The feature is straightforward and shouldn't take longer than four hours to get done for an experienced engineer.
However, i'm currently occupied with full-time obligations and probably won't start the next release development until mid September.

**Comment by KsAmJ** [comment]
Thanks for your reply

Can you include it on the next update?

Meanwhile I guess i could do a walk around by making a batch that replace
the DB slqlite file with a cleared one everyday.

Would that work? And if so which tables should be cleared in the DB?


As I was testing and cleared the tickets table but the system didn't manage
to work after so I belive there is something somewhere else

**Comment by mrf345** [comment]
> Can you include it on the next update?

Yes, hopefully it will be in the `0.9` release.

> Would that work? And if so which tables should be cleared in the DB?

The following SQL should do it:

```sql
delete from serials where number != 100;
```

So you can easily execute it with `sqlite3` CLI:

```bash
sqlite3 data.sqlite "delete from serials where number != 100;"
```

**Comment by mrf345** [comment]
I'm about to merge a PR that adds the feature, check out https://github.com/mrf345/FQM/pull/221#issue-480857221 for a demo.
