### ISSUE TITLE
Fixing updating user bug

### ISSUE THREAD

**Issue by bhong2002** [mrf345/FQM#2]
>>> add operator_id(integer) to table offices table on data.sqlite
	>>> edit data.py on Office class 

	class Office(db.Model):
	    __tablename__ = "offices"
	    id = db.Column(db.Integer, primary_key=True)
	    name = db.Column(db.Integer, unique=True)
	    timestamp = db.Column(db.DateTime(), index=True, default=datetime.utcnow)
	    prefix = db.Column(db.String(2))
	    operator_id = db.Column(db.Integer)
	
	    def __init__(self, name, prefix, operator_id):
	        self.name = name
	        self.prefix = prefix
	        self.operator_id = operator_id

	>>> edit /template/user_update.html
	>>> add this lines after line "59"
		<br>
		{{ render_field(form.offices, class="form-control") }}<br>
		<br><br>

**Comment by mrf345** [comment]
Hello  @bhong2002, thanks for the details.
Did you try it with the last updates ? i think the issue, is fixed already.

**Comment by bhong2002** [comment]
oh sorry . . .
