### ISSUE TITLE
Alias receipt not working

### ISSUE THREAD

**Issue by Nerdtality** [mrf345/FQM#229]
FQM beta 0.9

Alias names not changing on receipts, they stay as if they where default. The code doesn't look for an alias at this moment.

**Comment by Nerdtality** [comment]
Work around, edit app/printer.py and compile

**Comment by mrf345** [comment]
Nice catch! the printed ticket aliases were explicitly ignored by mistake after some refactoring done in a previous release. I've added more test coverage to catch it in the future. I'm about to merge a PR https://github.com/mrf345/FQM/pull/231 that resolves it.

Please do let me know if the issue persists.
