### ISSUE TITLE
FQM serials duplicate

### ISSUE THREAD

**Issue by Nerdtality** [mrf345/FQM#230]
FQM beta 0.9

Duplicate serials created under SQL file, see image. Happens after reset all and delete all. If you manually delete all, program fails to add new tickets to queue assuming it uses number:100 for something important?

![image](https://user-images.githubusercontent.com/19711169/93794602-e5dd3a80-fbfd-11ea-9dca-25a7e55ea8d8.png)

**Comment by mrf345** [comment]
Good catch!`100` tickets are just fillers, the system will ignore them, if you check out any of the `Serial` model methods you'll see them filtered out for example [here](https://github.com/mrf345/FQM/blob/master/app/database.py#L246-L248).

Come to think of it now 🤔 Probably that's not the cleanest approach. However, that's how it was implemented 3 years, and I didn't see an urgent need to refactor it. Is there a specific use-case that causes the program to fail?

**Comment by Nerdtality** [comment]
Not really, I messed around with the database a bit, wiped the Serial queue and the program failed to create tickets. Normal users should never have an issue unless you go about messing with the database lol

**Comment by mrf345** [comment]
No worries then, if it isn't broken, don't fix it 😀
