### ISSUE TITLE
Auto reload not remembered after logout/login

### ISSUE THREAD

**Issue by skymaker-c2is** [mrf345/FQM#237]
**Describe the bug**
The auto-reload duration and status is not remembered after logout. It would be good if the auto reload status and duration would be saved on the server side for each user.

**To Reproduce**
Steps to reproduce the issue:
1. Login
2. Go to the ticket overview
3. Click "auto reload"
4. Change duration
5. Logout
6. Login

**Please complete the following information:**
 - Operating System (OS): Windows 10 (Client)
 - Browser Firefox 81.0.1
 - FQM Version 0.9

**Comment by mrf345** [comment]
Nice catch, and thanks for the well-detailed issue! I think moving it to the database is a bit of an overkill, especially if we can resolve it easily through the front-end.

It seems we're using [`sessionStorage`](https://developer.mozilla.org/en-US/docs/Web/API/Window/sessionStorage)  in the [`auto_reload.js`](https://github.com/mrf345/FQM/blob/master/static/auto_reloader.js) script, which gets cleared whenever the user's browsing session's ended. We can use [`localStorage`](https://developer.mozilla.org/en-US/docs/Web/API/Window/localStorage) instead, which will persist regardless of browsing sessions.

**Comment by mrf345** [comment]
I'm about to merge a PR that resolves it. Please do let me know if the issue persists.
