### ISSUE TITLE
Autorun

### ISSUE THREAD

**Issue by danfossi** [mrf345/FQM#26]
Hi,
I'd like to know if is it possible to start the application 
- from CLI passing parameters (eg IP, language, port)? 
- without having Xorg installed ? (Linux only)

**Comment by mrf345** [comment]
Hi @danfossi , CLI wasn't supported unfortunately. I've just merged a PR https://github.com/mrf345/FQM/pull/27 that adds the feature.

**How-to:**
- After installing the dependencies with `pip install -r requirements.txt`
- You can run it with `python run.py --cli`
> If no `port` is passed it will default to a random port.
> If no `ip` is passed it will default to `127.0.0.1`.

**Available options**
```bash
Usage: run.py [OPTIONS]

Options:
  --cli        To use commandline interface instead of GUI.
  --quiet      To silence web server logs.
  --ip TEXT    IP address to stream the service on.
  --port TEXT  Port to stream the service through.
  --help       Show this message and exit.
```
