### ISSUE TITLE
No tts announcement with or without internet

### ISSUE THREAD

**Issue by abdou0202** [mrf345/FQM#265]
**Describe the bug**
When checking the announcement language. The whole sound shut down
I've tried both the exe program and the code. Both have the same issue 

**Please complete the following information:**
 - Operating System (OS): [Windows 10]
 - Browser [Firefox. Edge. Chrome]
 - FQM Version [0.9]

**Comment by opioidmind** [comment]
Have u found a fix yet ?

**Comment by mrf345** [comment]
Just a dependency that needs to be kept up to date.
