### ISSUE TITLE
How to build the project for normally user

### ISSUE THREAD

**Issue by Amrgoudaelsaid** [mrf345/FQM#274]
Dear Mohamed,

first, I would like to thank you for your great effort for help us :)
second, how can I build the project to be ready for use after changing some features such as the below request: ( Add header and sub-header fields to printed tickets #254 )

and the Instructions on the below topic: ( Instructions to compile exe and FQA #7 ) are not clear enough for the non-tech user.

**Comment by Amrgoudaelsaid** [comment]
step py step please

**Comment by mrf345** [comment]
Hi, thanks for the issue, unfortunately running the project with `PyInstaller` executables (.exe...) is no longer supported, always been a struggle to get to work across operating systems, and very time-consuming.

The instructions provided in previous comments are certainly very outdated, and most likely won't work without long sessions of debugging, so unless it's an absolute necessity for your use-case, I would highly recommand you to stay away, or probably try a different approach, maybe [nuitka](https://nuitka.net/pages/overview.html)

On persisting changes before release, you'll just need to include your `data.sqlite` file with the project, it should contain all the changes you've made.

**Comment by Amrgoudaelsaid** [comment]
Thanks for your response bro. 

I am replying to let you know there is a way to build the final source code.
