### ISSUE TITLE
Arabic Sound on display page

### ISSUE THREAD

**Issue by Husam1990** [mrf345/FQM#281]
Hi dears ,,
have a nice well and thanks for your efforts ,, 
I change language to Arabic from start page ,, but sound on display page is English ?!
have you any idea !

BR

**Comment by mrf345** [comment]
Hi, you too, thanks.

Navigate to Customization > Display Screen > Notification Sound, and then select Arabic:
![image](https://user-images.githubusercontent.com/26286907/198899857-29443af9-903a-435f-a744-3051c47ef23d.png)
