### ISSUE TITLE
Operator menu wont start after clicking the "Let's start" button

### ISSUE THREAD

**Issue by efraintejerina** [mrf345/FQM#290]
Hi dear

After logging in with the operator user and pressing the "Let's Start" button, we are greeted with an error message saying "Something is wrong". 

Steps to reproduce the issue:
1. Execute on cmd: py run.py
2. Log in with a operator rol
3. click on let's start
4. the site shows an error message "Error: something wrong , or the page is non-existing" and won't allow me to continue further. 

 - Operating System (OS): Windows 10
 - Browser Chrome 117, Firefox 117
 - FQM Version 0.9

I'm very thankfull for your help and await your answer.

![error fqm](https://github.com/mrf345/FQM/assets/143751745/b6a92998-f591-4079-9bd2-8d48c0dab22f)

**Comment by zeadriano** [comment]
I have the same problem on debian 11. I can log in with administrator and monitor, but I can't log in with any operator.

my configuration:
OS: Debian 11
python version 3.9
Browser Chrome 117, Firefox 117
FQM Version 0.9
Installation: Without docker
command: python3 run.py --cli

I tried with and without a python environment and unfortunately the result is the same.

efraintejerina did you solve your problem?

**Comment by mascimax** [comment]
hi,
I have the same problem on ubuntu 22.04
my configuration:
OS: ubuntu 22.04
python version 3.7
FQM Version 0.9
Installation: docker (same problem also Without docker)

i find also error on log when try to enter as operator:

gunicorn -w $(nproc --all) -b $APP_HOST:$APP_PORT $APP_PATH
gunicorn -w $(nproc --all) -b $APP_HOST:$APP_PORT $APP_PATH
werkzeug.exceptions.InternalServerError: 500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.

werkzeug.exceptions.InternalServerError: 500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.

**Comment by mascimax** [comment]
> Hi dear
> 
> After logging in with the operator user and pressing the "Let's Start" button, we are greeted with an error message saying "Something is wrong".
> 
> Steps to reproduce the issue:
> 
> 1. Execute on cmd: py run.py
> 2. Log in with a operator rol
> 3. click on let's start
> 4. the site shows an error message "Error: something wrong , or the page is non-existing" and won't allow me to continue further.
> 
> * Operating System (OS): Windows 10
> * Browser Chrome 117, Firefox 117
> * FQM Version 0.9
> 
> I'm very thankfull for your help and await your answer.
> 
> ![error fqm](https://private-user-images.githubusercontent.com/143751745/267773421-b6a92998-f591-4079-9bd2-8d48c0dab22f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUzODU5NjMsIm5iZiI6MTcwNTM4NTY2MywicGF0aCI6Ii8xNDM3NTE3NDUvMjY3NzczNDIxLWI2YTkyOTk4LWY1OTEtNDA3OS05YmQyLThkNDhjMGRhYjIyZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExNlQwNjE0MjNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04NGYyMGMzNmEzNzdhYjQ5MzRiY2QwNGIyZDU1MzMzMzIxZThlZDYwNDhhOWNkMmY2MjE5YzY0MTI1NjlmMDUxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ZLZZdRDCXDpolcoWK7NyYEWP26l3tOriEQwwK4D_VqI)

You solve this problem?
