### ISSUE TITLE
Requirement error

### ISSUE THREAD

**Issue by danfossi** [mrf345/FQM#46]
Hi,
after the "Major refactoring for init" commit some error comes up:

1) During **./installer.sh --install**:
`ERROR: flake8 3.7.9 has requirement pycodestyle<2.6.0,>=2.5.0, but you'll have pycodestyle 2.3.1 which is incompatible.
ERROR: flake8 3.7.9 has requirement pyflakes<2.2.0,>=2.1.0, but you'll have pyflakes 1.5.0 which is incompatible.
`

P.S: I really appreciate your job!

**Comment by mrf345** [comment]
Hi @danfossi  thanks for the heads up. That warning is the result of some outdated requirements that were conflicting with `flake8` package.  I've deleted them in this PR https://github.com/mrf345/FQM/pull/47

My pleasure 🙌
