### ISSUE TITLE
Template layout modifications...

### ISSUE THREAD

**Issue by cliffdude** [mrf345/FQM#49]
First I have to say Great Project.
What would be the procedure to modify the existing templates or is this very difficult. I have very limited python knowlage but I don't think that would be a problem.  I have 0.6 running on Windows with the .zip download, works great. I can switch to linux if a recomplie is necessary.

Richard

**Comment by mrf345** [comment]
Thanks @cliffdude , glad you've liked it!

Customizing a template should be a straight forward implementation. If you're familiar with Jinja2 templates and JQuery, it will be a walk in the park. If not, i'm happy to assist you through implementing it as much as my time allows.

"Compiling" will be needed if you have to generate `.exe` file, if not then you can run it from the source on windows too. Just make sure Python 3.7 is installed and follow the [instructions](https://github.com/mrf345/FQM#--from-the-source).

Is there a specific template that you want to customize and what type of customization you're aiming for ?

**Comment by cliffdude** [comment]
@mrf345 Thank you for your reply, I have zero jinja2 knowlage and very little jquery knowlage but if you point out where to look and get started I can probably figure it out. As far as the modifications themselves are concerned I would like too move stuff around a bit, remove que queued tickes info and make the video screen bigger. 
Is there a way to quickly call the next ticket, possibly a URL that could be sent from a button?

**Comment by mrf345** [comment]
My pleasure! The front-end block responsible for displaying the video can be found in the [display template](https://github.com/mrf345/FQM/blob/master/templates/display.html#L185-L195). Probably just changing the `height` and `width` will do. Come to think of it that should have been included in the customization settings, my bad. Probably will add it to the backlog.

The link to pull tickets globally with is `/pull`  if it's specific to a task then you'll have to pass the task and office IDs. `/pull/<task_id>/<office_id>` the back-end endpoint responsible for that can be found [here](https://github.com/mrf345/FQM/blob/master/app/views/core.py#L319-L323).

**Comment by mrf345** [comment]
@cliffdude I'm about to merge a PR https://github.com/mrf345/FQM/pull/82 that will resolve the issue.
