### ISSUE TITLE
Not Announcing the name

### ISSUE THREAD

**Issue by Abel316** [mrf345/FQM#5]
Good day,

Please assist as when i pull a ticket on the FQM system it displays the next name but it does not announce it.... there is no audio.

Please help...

**Comment by mrf345** [comment]
Hi @Abel316, There's a [reported issue](https://github.com/pndurette/gTTS/issues/138), which effects Google text-to-speech library, that FQM depends on. To solve the issue you'll have to update the faulty library by `pip install -U gtts-token`.

**Comment by athernadeem** [comment]
hi sir facing issue with ticket number sound could you please help me regarding this.
