### ISSUE TITLE
Adjusting printed ticket font size

### ISSUE THREAD

**Issue by fabioferrini** [mrf345/FQM#50]
how can i change the font size on printed ticket?

**Comment by mrf345** [comment]
I plan to add a customization option for that in the upcoming release. But until then, you can manually modify the `height=` and `width=` used in [these lines](https://github.com/mrf345/FQM/blob/master/app/printer.py#L52-L64) to fit your specific printer width and height.

**Comment by AndreaGambaretto** [comment]
I tried to edit the same file printer.py to customize the tiket content.
I modified the line #53 writing this
_printer.text("**Newname**\n")_
but nothing changed.
When i print, i have the same default content again.
I'm doing a mistake somewhere?

**Comment by mrf345** [comment]
@fabioferrini  I'm about to merge a PR that implements this feature https://github.com/mrf345/FQM/pull/81

@AndreaGambaretto I'm using [python-escpos](https://github.com/python-escpos/python-escpos) library to generate the `esc/pos` instructions. follow their [documentation](https://python-escpos.readthedocs.io/en/latest/api/escpos.html).
