### ISSUE TITLE
Display Multiple Office

### ISSUE THREAD

**Issue by Jaedric17** [mrf345/FQM#51]
How to customize the code for windows user I want to display the 5 office in one screen or on screen display but the con, cot, cott stream code I can't find where is it declared, if I'm not wrong this is with the exe file in python code? Can you help me about this issue?

**Comment by mrf345** [comment]
Hi @Jaedric17 

The current display screen implementation shows tickets from all offices. I plan to cleanup and refactor `/feed` to get tickets for specific office so we can have a display screen for each office or combination of them.

So probably i'm not understanding you objective correctly. You want to customize the display screen to all show offices ? do you mean attaching the office to the ticket itself ?

Certainly my pleasure, happy to help.

**Comment by Jaedric17** [comment]
Yes that's what I mean to display 5 teller/offices in different column to avoid the customer miss them tickets...like our customer in one day probably more than 2000 per day. so if the 5 teller call their customer at one time, the ticket number pop only a second because the column of offices is only one.

**Comment by Jaedric17** [comment]
Thank you very much for your response.. :)

**Comment by mrf345** [comment]
This issue has been addressed with an already merged PR https://github.com/mrf345/FQM/pull/79 I forgot to mention it there.
My pleasure 👍
