### ISSUE TITLE
No sound on Display

### ISSUE THREAD

**Issue by rubelhaider** [mrf345/FQM#6]
I have uploaded a dingdong.wav  and select it as a notification sound but its not working. I am not getting any sound on display when i pull a ticket. Please help me out with this problem. Thanks

**Comment by bhong2002** [comment]
what browser are you using?... try it on firefox browser...

**Comment by rubelhaider** [comment]
I have already tried with firefox. but the result is same, no notification sound on display

**Comment by mrf345** [comment]
Hi guys, I've put a new[ release 0.4.3](https://fqms.github.io/#download), that's up-to-date with this repo and solves this problem.
