### ISSUE TITLE
Instructions to compile exe and FQA

### ISSUE THREAD

**Issue by ma0c** [mrf345/FQM#7]
After do some modifications, how you create a new .exe?

**Comment by liqinnetgain** [comment]
What could be the issue?

python run.py get the err msg 

run.py: cannot connect to X server

**Comment by mrf345** [comment]
@liqinnetgain It comes with a GUI built with PySide, so if you're running Linux without an X server it won't run.

**Comment by Amrgoudaelsaid** [comment]
Can you provide us with simple for the below step:

3- Make sure to modify [run.spec](https://github.com/mrf345/FQM/blob/master/run.spec) to be suited for your own environment settings, things to look out for:
Modify the project directory [here](https://github.com/mrf345/FQM/blob/master/run.spec#L7) to suite your environment
Make sure to copy the [icon file](https://github.com/mrf345/FQM/blob/master/static/images/favicon.ico) to the project main directory.
