### ISSUE TITLE
No sound problem on Display

### ISSUE THREAD

**Issue by rubelhaider** [mrf345/FQM#8]
Dear developer,
Recently No sound problem has been arise again. I am using your latest version of FQM 0.4.3 It was ok few days ago. What could be the problem. Please give me a clue.

**Comment by mrf345** [comment]
Hi @rubelhaider , there's an [issue](https://github.com/pndurette/gTTS/issues/151) caused by change in Google text-to-speech API. The issue's already fixed, if you're running the project from the source-code, just update the failing package by `pip install -U gtts-token` and it should work.

**Comment by yassin121** [comment]
Dear developer,
Recently No sound problem has been arise again. I am using your latest version of FQM 0.4.3 It was ok few days ago. What could be the problem. Please give me a clue

**Comment by mrf345** [comment]
@rubelhaider @yassin121 , A new release that fix it is finally out [here](https://sourceforge.net/projects/free-queue-manager/files/FQM%200.5/FQM_05_Windows.zip/download).
