### ISSUE TITLE
Using a regular USB printer 

### ISSUE THREAD

**Issue by ms8277** [mrf345/FQM#9]
Hi,
We're trying to use a regular USB printer for testing purpose before purchasing a POS printer, but that doesn't seems to work. Is there any way we can test the printing functionality using a regular printer, like a universal POS driver?

Thanks

**Comment by ms8277** [comment]
Is there any recommended POS printer to use with the system?

**Comment by mrf345** [comment]
Hi @ms8277 sorry for the delayed. Short answer for the regular printer support, is no. 
Long one it has to do with the library i've used to print on unix-like systems. `python-escpos` the library will send `ESC` instructions to the printer, which's only supported by `POS` printers as far as i know.

The printer i've used for development and testing, is the cheapest printer i could find online `ZJ-5890K` 58mm USB printer. Other users have reported success with some Epson printers but i've not tried it myself.
