### ISSUE TITLE
ticket printer erorr

### ISSUE THREAD

**Issue by basit-Ali1122** [mrf345/FQM#91]
My POS thermal printer is add successfully tested. Im using Black copper bc85 series printer but when i click on a task in touch screen it generate this error         
Traceback (most recent call last):
  ****File "E:\SSQM\SSQM\app\views\core.py", line 122, in serial
    ip=current_app.config.get('LOCALADDR'))
TypeError: print_ticket_windows() missing 1 required positional argument: 'l'
##### 2020-02-27 19:55:08.655894 #####****

and secreen return to home page 

please hep me out

**Comment by ahmedmkr** [comment]
i have an error with test printer
1erst problem is ; ''C:\user\lenovo\destock\FQM\temps4\is currently being printed''
2sg; ''clenup is done: press ok to exit''
3sd: in cmd  :''Cannot find C: \ Users \ lenovo \ Desktop \ FQM \ temp6''

please help me to configurate my printer
