### ISSUE TITLE
Single row queue management

### ISSUE THREAD

**Issue by picsldev** [mrf345/FQM#96]
![Fila única](https://totalpack.cl/wp-content/uploads/2018/10/kit-turno-simple.png)  

----  

In many small businesses, the implementation of queue management has been tried to simplify as much as possible.

Its basic components are:

1. A number dispenser with a pre-printed roll of numbered tickets, which the customer picks up the moment they arrive at the store. [Detaill](https://totalpack.cl/wp-content/uploads/2018/09/Rollos-EstandarTRANSP-1.png)

1. A basic shift screen. [1](https://totalpack.cl/wp-content/uploads/2018/10/Turno-2-digitos-1TRANSP.png), [2](https://totalpack.cl/wp-content/uploads/2018/10/Turno-modulo-1TRANSP.png), [3](https://totalpack.cl/wp-content/uploads/2018/10/turno-simple-letra-2TRANSP.png)

1. Push buttons / button to update the number to attend, on the shift screen.

**FQM**, with some changes to its workflow, could also meet the needs of these small businesses.

How can I help implement this idea?  

Regardless of the decision to accept this issue or not, a good job is being done with this project :-)  

----

**[Spanish / Español]**

En muchos negocios pequeños, la implantación de una gestión de colas se ha intentado simplificar al máximo.

Sus componentes básicos son:  

1. Un dispensador de números con un rollo preimpreso de tiques numerados, que el cliente retira en el momento que accede al local. [Detalle](https://totalpack.cl/wp-content/uploads/2018/09/Rollos-EstandarTRANSP-1.png)

1. Una pantalla de turno básica. [1](https://totalpack.cl/wp-content/uploads/2018/10/Turno-2-digitos-1TRANSP.png), [2](https://totalpack.cl/wp-content/uploads/2018/10/Turno-modulo-1TRANSP.png), [3](https://totalpack.cl/wp-content/uploads/2018/10/turno-simple-letra-2TRANSP.png)

1. Pulsadores para actualizar el número a atender, en la pantalla de turnos. 

**FQM**, con algunos cambios en su flujo de trabajo, también podría cubrir las necesidades de estos pequeños comercios.

¿Cómo puedo ayudar a implementar esta idea?

Independientemente de la decisión de aceptar o no este issue, se está haciendo un buen trabajo con este proyecto :-)

**Comment by mrf345** [comment]
First of all, sorry for the late reply. I had to take some times off to work on other projects.

`FQM` was initially implemented as a smart queuing software solution for small sized public offices that already have most of the devices needed for that task:
1. Personal computer or laptop.
2. Smart TV or large display.
3. A Point-of-sale POS printer.

Hopefully that explains the existing emphasis on `Offices <-> Tasks` relations and how it might seem unintuitive for a single row queue. Although personally i can't see, how the current implementation won't work with a single row queue. If you were to use a single office with many tasks. The only disadvantage in that approach is the unnecessary abstract and configuration that a single row queue won't take advantage of. So if hiding the additional configuration and `Offices <-> Tasks` relations setup will lead to a better user experience, then i think adding a simple `flag setting` to do that will be a more than welcome addition. And i'll be happy to provide more technical details if someone wants to take over this one.

Regarding the devices and hardware you've shared screenshots of, `FQM` is very unlikely to support any of the traditional queuing hardware for few reasons:

- *hardware and supporting hardware is expensive*: to attempt to add support to any hardware we'll start with the cost of buying the hardware itself and shipping it. Supporting the hardware cross-platform Windows 7, 10, Linux... is difficult and very time consuming. Multiply that effort and cost with every device.

- *Less people are going to benefit*: Not everyone but at least majority of small offices have some sort of a compute and a large screen. But it's less likely to find an LCD Screen.


Thanks for sharing your thoughtful suggestions, Please let me know if i missed any point ☺️

**Comment by picsldev** [comment]
> First of all, sorry for the late reply. I had to take some times off to work on other projects.

No problem. We all combine work and pleasure :-)

> `FQM` was initially implemented as a smart queuing software solution for small sized public offices that already have most of the devices needed for that task:
> 
> 1. Personal computer or laptop.
> 2. Smart TV or large display.
> 3. A Point-of-sale POS printer.

Okay. This is where I think my explanation was not as complete as I thought.

For a single queue, we still need a PC / Laptop and also a screen (smart TV or large display) to show the call order.

In both cases, `FQM` already correctly manages both PC / laptop and different types of screens.

Where do you have to implement that flag that you point out later?

This flag must be implemented to be able to choose between the possible ways in which a customer generates the ticket with the order number that has been touched.

That flag has to allow the current model, logically, which implies that no extra code is modified, only the creation of the flag.

My proposal is to give a first option to that flag, which would be the following:
1. Verify that there is only one queue
1. Choose between:
  a) Maintain a touchpad that prints a ticket (a problem with Covid19)
  b) Deactivate the touch panel and ticket printing, so that the visitor can manually remove a ticket, already printed, using a paper system similar to the one shown in [this image](https://totalpack.cl/wp-content/uploads/2018/09/Rollos-EstandarTRANSP-1.png)

![](https://totalpack.cl/wp-content/uploads/2018/09/Rollos-EstandarTRANSP-1.png)

With this flag change, the rest of the `FQM` code (I think) would stay the same, but would extend the experience when it comes to managing single queues on a service.

In the original explanation, by including images of gadgets that have NOTHING to do with `FQM`, I misled you in the wrong direction.

No need to include support for new gadgets at all. My apologies for not having explained me better.

> 
> Thanks for sharing your thoughtful suggestions, Please let me know if i missed any point
>

If my explanation raises any further questions, I would appreciate it if you could tell me, in order to finish defining the objective of this issue.

From here, if you give me the initial clues, I would try to implement this flag myself and thus move forward.

Thx for your time @mrf345 !

**Comment by mrf345** [comment]
Hello @picsldev

Sorry again for the delayed reply. I had to resolve some critical bugs and increase the test coverage to hopefully help us avoid creating more bugs with this new implementation.

Initially I thought it would be a good idea to start with documenting parts of the code-base and how to go about implementing stuff, like [adding flag setting](https://github.com/mrf345/FQM/blob/master/docs/settings.md) but then realized that it will just take forever. And most of it will change drastically as we get closer to the first stable release `1.0`.

So i decided to implement an initial PR https://github.com/mrf345/FQM/pull/144 that we can both contribute to and iterate over. As far as i can tell the current implementation meets all the requirements proposed  in your last comment, so give it a try and please let me know if i missed any objective. **NOTE:** the change isn't merged with `master` yet, so you'll have to either checkout the PR itself or the [testing branch](https://github.com/mrf345/FQM/tree/testing).

My pleasure ☺️

**Comment by mrf345** [comment]
Hi @picsldev 

 I'm about to merge the PR https://github.com/mrf345/FQM/pull/144, so i can include it in the next release `0.8`. Feel free to open a separate issue if there's any defects or unmet objectives.
